lib/storex_web/router.ex
defmodule StorexWeb.Router do
  use StorexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug StorexWeb.Plugs.Cart
    plug StorexWeb.Plugs.ItemsCount
    plug StorexWeb.Plugs.ItemsTotalPrice
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StorexWeb do
    pipe_through :browser # Use the default browser stack

    get "/", BookController, :index
    get "/books/:id", BookController, :show

    resources "/carts", CartController, singleton: true, only: [:show, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", StorexWeb do
  #   pipe_through :api
  # end
end

lib/storex/application.ex
defmodule Storex.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Storex.Repo, []),
      # Start the endpoint when the application starts
      supervisor(StorexWeb.Endpoint, []),
      # Start your own worker by calling: Storex.Worker.start_link(arg1, arg2, arg3)
      # worker(Storex.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Storex.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    StorexWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/storex/repo.ex
defmodule Storex.Repo do
  use Ecto.Repo, otp_app: :storex

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/storex/sales/cart.ex
defmodule Storex.Sales.Cart do
  use Ecto.Schema
  import Ecto.Changeset
  alias Storex.Sales.Cart

  schema "sales_carts" do
    has_many :line_items, Storex.Sales.LineItem
    timestamps()
  end


  @doc false
  def changeset(cart, attrs) do
    cart
    |> cast(attrs, [])
    |> validate_required([])
  end
end

lib/storex/sales/line_item.ex
defmodule Storex.Sales.LineItem do
  use Ecto.Schema
  import Ecto.Changeset
  alias Storex.Sales.LineItem

  schema "sales_line_items" do
    belongs_to :cart, Storex.Sales.Cart
    belongs_to :book, Storex.Store.Book
    field :quantity, :integer
    timestamps()
  end

  @doc false
  def changeset(line_item, attrs) do
    line_item
    |> cast(attrs, [:quantity])
    |> validate_required([:quantity])
  end
end

lib/storex/sales/sales.ex
defmodule Storex.Sales do
  import Ecto.Query, warn: false
  alias Storex.Repo
  alias Storex.Sales.{Cart, LineItem}

  def create_cart(attrs \\ %{}) do
    %Cart{}
      |> Cart.changeset(attrs)
      |> Repo.insert()
  end

  def get_cart!(id) do
    Repo.get!(Cart, id)
  end

  def add_book_to_cart(book, cart) do
    line_item = Repo.get_by(LineItem, book_id: book.id, cart_id: cart.id)

    if line_item do
      line_item
        |> LineItem.changeset(%{quantity: line_item.quantity + 1})
        |> Repo.update()
    else
      %LineItem{book_id: book.id, cart_id: cart.id}
        |> LineItem.changeset(%{quantity: 1})
        |> Repo.insert()
    end
  end

  def remove_book_from_cart(book, cart) do
    line_item = Repo.get_by!(LineItem, book_id: book.id, cart_id: cart.id)

    if line_item.quantity > 1 do
      line_item
        |> LineItem.changeset(%{quantity: line_item.quantity - 1})
        |> Repo.update()
    else
      Repo.delete!(line_item)
    end
  end

  def list_line_items(cart) do
    LineItem
      |> where(cart_id: ^cart.id)
      |> preload(:book)
      |> Repo.all()
  end

  def line_items_quantity_count(items) do
    Enum.reduce(items, 0, fn(item, acc) -> acc + item.quantity end)
  end

  def line_items_total_price(items) do
    Enum.reduce(items, Decimal.new(0), fn(item, acc) -> 
      quantity = Decimal.new(item.quantity)
      partial = Decimal.mult(quantity, item.book.price)

      Decimal.add(acc, partial)
    end)
  end
end

lib/storex/store/book.ex
defmodule Storex.Store.Book do
  use Ecto.Schema
  import Ecto.Changeset


  schema "store_books" do
    field :description, :string
    field :image_url, :string
    field :price, :decimal
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(book, attrs) do
    book
    |> cast(attrs, [:title, :description, :price, :image_url])
    |> validate_required([:title, :description, :price, :image_url])
    |> validate_number(:price, less_than: 100)
  end
end

lib/storex/store/store.ex
defmodule Storex.Store do
  alias Storex.Repo
  alias Storex.Store.Book

  def list_books() do
    Repo.all(Book)
  end

  def get_book(id) do
    Repo.get(Book, id)
  end

  def create_book(attrs) do
    %Book{}
      |> Book.changeset(attrs)
      |> Repo.insert()
  end
end

lib/storex_web/controllers/book_controller.ex
defmodule StorexWeb.BookController do
  use StorexWeb, :controller
  alias Storex.Store

  def index(conn, _params) do
    render conn, "index.html", books: Store.list_books()
  end

  def show(conn, %{"id" => book_id}) do
    render conn, "show.html", book: Store.get_book(book_id)
  end
end

lib/storex_web/controllers/cart_controller.ex
defmodule StorexWeb.CartController do
  use StorexWeb, :controller
  alias Storex.Sales
  alias Storex.Store
  alias StorexWeb.Plugs

  def show(conn, _params) do
    cart = Plugs.Cart.get(conn)
    items = Sales.list_line_items(cart)
    total = Sales.line_items_total_price(items)

    render conn, "show.html", items: items, total: total
  end

  def create(conn, %{"book_id" => book_id}) do
    cart = Plugs.Cart.get(conn)
    book = Store.get_book(book_id)
    Sales.add_book_to_cart(book, cart)

    redirect(conn, to: cart_path(conn, :show))
  end

  def delete(conn, %{"book_id" => book_id}) do
    cart = Plugs.Cart.get(conn)
    book = Store.get_book(book_id)
    Sales.remove_book_from_cart(book, cart)

    redirect(conn, to: cart_path(conn, :show))
  end
end

lib/storex_web/controllers/page_controller.ex
defmodule StorexWeb.PageController do
  use StorexWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/storex_web/views/book_view.ex
defmodule StorexWeb.BookView do
  use StorexWeb, :view
  import StorexWeb.Helpers.PriceFormatter
end

lib/storex_web/views/cart_view.ex
defmodule StorexWeb.CartView do
  use StorexWeb, :view
  import StorexWeb.Helpers.PriceFormatter
end

lib/storex_web/views/error_view.ex
defmodule StorexWeb.ErrorView do
  use StorexWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/storex_web/views/layout_view.ex
defmodule StorexWeb.LayoutView do
  use StorexWeb, :view
  import StorexWeb.Helpers.PriceFormatter

  def items_count(conn) do
    StorexWeb.Plugs.ItemsCount.get(conn)
  end

  def items_total_price(conn) do
    StorexWeb.Plugs.ItemsTotalPrice.get(conn)
      |> format_price
  end
end

lib/storex_web/views/page_view.ex
defmodule StorexWeb.PageView do
  use StorexWeb, :view
end

lib/storex_web/templates/book/index.html.eex
<section>
  <ul class="grid">
    <%= for book <- @books do %>
      <li class="grid-item">
        <div class="book book-small">
          <%= link to: book_path(@conn, :show, book.id) do %>
            <img class="book__image" src="<%= book.image_url %>" alt="">
            <h2 class="book__title"><%= book.title %></h2>
          <% end %>
          <span class="book__price"><%= format_price(book.price) %></span>
        </div>
      </li>
    <% end %>
  </ul>
</section>

lib/storex_web/templates/book/show.html.eex
<h1> <%= @book.title %> </h1>

<div class="book book-hero">
  <img class="book__image" src="<%= @book.image_url %>" alt="">
  <p class="book_description"><%= @book.description %></p>
</div>

<div class="value-tag">
  <h2 class="value-tag__title">Price: </h2>
  <span class="value-tag__content"><%= format_price(@book.price) %></span>
</div>

<%= link "Add to cart",
    to: cart_path(@conn, :create, book_id: @book.id),
    method: :create,
    class: "button button-primary" %>

lib/storex_web/templates/cart/show.html.eex
<h1> Cart </h1>

<ul class="cart-items">
  <%= for item <- @items do %>
    <li class="cart-item">
      <img class="cart-item__image" src="<%= item.book.image_url %>">
      <div class="cart-item__title">
        <span><%= item.book.title %></span>
      </div>

      <div class="cart-item__units">
        <div class="value-tag">
          <h2 class="value-tag__title">Quantity</h2>
          <span class="value-tag__content">
            <div class="step minus">
              <%= link "-", to: cart_path(@conn, :delete, book_id: item.book_id),
                  method: :delete %>
            </div>
            <div class="step plus">
              <%= link "+", to: cart_path(@conn, :create, book_id: item.book_id),
                  method: :create %>
            </div>
            <br>
            <%= item.quantity %>
          </span>
        </div>
      </div>

      <div class="cart-item__price">
        <div class="value-tag">
          <h2 class="value-tag__title">price</h2>
          <span class="value-tag__content"><%= format_price(item.book.price) %></span>
        </div>
      </div>

      <div class="value-tag">
        <h2 class="value-tag__title">total</h2>
        <span class="value-tag__content"><%= format_price(@total) %></span>
      </div>
    </li>
  <% end %>
</ul>

lib/storex_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Welcome to Storex</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="main-nav">
      <a class="main-nav__logo" href="/"></a>

      <ul class="main-nav__links">
        <%= if items_count(@conn) do %>
          <li>
            <%= link to: cart_path(@conn, :show) do %>
              cart
              <span class="badge"><%= items_count(@conn) %> items - <%= items_total_price(@conn) %> </span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>

    <main role="main" class="content">
      <%= if message=get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= message %></p>
      <% end %>

      <%= if message=get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= message %></p>
      <% end %>

      <%= render @view_module, @view_template, assigns %>
    </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/storex_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>